# Generated by Django 5.2.8 on 2025-11-21 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_rename_name_task_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Pending', '待處理'), ('In progress', '處理中'), ('Done', '完成'), ('Delete', '刪除')], default='Pending', max_length=20),
        ),
    ]
